[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-welcomeplus"
version = "0.0.8"
description = "Welcome title plugin for Endstone servers"
authors = [
    { name = "ErwanScraft" }
]
dependencies = [
    "PyYAML>=6.0"
]

[project.entry-points."endstone"]
welcomeplus = "welcomeplus:WelcomePlusPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/welcomeplus"]